// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awxfanbicposoqnbwvsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3eGZhbmJpY3Bvc29xbmJ3dnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzYyNzIsImV4cCI6MjA2ODQ1MjI3Mn0.HGdKq-FCyDsi0sHl_WB_HfY56Xzesn8bE3G6H-dtQ5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});